### ISSUE TITLE
webview library upgrade

### ISSUE THREAD

**Issue by whatamelon** [salondecode/kopo#5]
webview library 1.0.0이 배포되었습니다.
이에 맞춰 1.0.0 upgrade 진행 부탁드립니다.

항상 잘 사용하고 있습니다. 감사합니다. XD

**Comment by proghjy** [comment]
@whatamelon 잘 이용하고 계신다니 감사합니다 🙇‍♂️ 냉큼 업데이트 반영하도록 하겠습니당~ 😉

**Comment by proghjy** [comment]
@whatamelon 해결했어요~

**Comment by whatamelon** [comment]
넵! 감사합니다!
