### ISSUE TITLE
위경도 데이터

### ISSUE THREAD

**Issue by MarioMott** [salondecode/kopo#8]
주소와 함께 위경도 데이터도 함께 리턴해주실수 없는가요?

**Comment by proghjy** [comment]
안녕하세요 @MarioMott 님
해당 패키지는 [다음우편번호서비스](http://postcode.map.daum.net/guide)를 이용하고 있습니다.
아쉽게도 반환되는 데이터에 위경도 정보는 없네요

**Comment by MarioMott** [comment]
답변 감사합니다.
